version: '2'

services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000"    