version: '3.5'

services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    depends_on:
      - app  
  redis:
    image: 'redis:7.2-rc2-alpine'
    ports:
      - "6379"    
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: "always"  